/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VehicleEditor.java
 *
 * Created on 26-Mar-2009, 15:02:43
 */

package vehicles.gui;

import java.awt.BorderLayout;
import vehicles.processing.Embedded;
import vehicles.*;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import processing.core.*;

/**
 *
 * @author Niall O'Hara
 */
public class VehicleEditor extends javax.swing.JFrame {

    /** Creates new form VehicleEditor */
    public VehicleEditor(java.awt.Frame parent) {

        embed = new Embedded();
        initComponents();
        // important to call this whenever embedding a PApplet.
        // It ensures that the animation thread is started and
        // that other internal variables are properly set.
        embed.init();
    }

    @Action public void cancel() {
        dispose();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer = new JTabbedPane();
        tab_Properties = new JPanel();
        panel_VehicleName = new JPanel();
        vehicleName_jTextField = new JTextField();
        panel_SelectedVehicle = new JPanel();
        selectedVehicle_jComboBox = new JComboBox();
        panel_VehicleDescription = new JPanel();
        jScrollPane6 = new JScrollPane();
        vehicleDescription_jTextArea = new JTextArea();
        panel_Author = new JPanel();
        author_jTextField = new JTextField();
        panel_Preview = new JPanel();
        panel_Processing = new JPanel();
        tab_Design = new JPanel();
        button_Save = new JButton();
        button_SaveAs = new JButton();
        button_Cancel = new JButton();

        ResourceMap resourceMap = Application.getInstance(VehiclesApp.class).getContext().getResourceMap(VehicleEditor.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        tabContainer.setName("tabContainer"); // NOI18N

        tab_Properties.setName("tab_Properties"); // NOI18N

        panel_VehicleName.setBorder(BorderFactory.createTitledBorder(resourceMap.getString("panel_VehicleName.border.title"))); // NOI18N
        panel_VehicleName.setName("panel_VehicleName"); // NOI18N

        vehicleName_jTextField.setName("vehicleName_jTextField"); // NOI18N

        GroupLayout panel_VehicleNameLayout = new GroupLayout(panel_VehicleName);
        panel_VehicleName.setLayout(panel_VehicleNameLayout);
        panel_VehicleNameLayout.setHorizontalGroup(
            panel_VehicleNameLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(vehicleName_jTextField, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panel_VehicleNameLayout.setVerticalGroup(
            panel_VehicleNameLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(vehicleName_jTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        panel_SelectedVehicle.setBorder(BorderFactory.createTitledBorder(resourceMap.getString("panel_SelectedVehicle.border.title"))); // NOI18N
        panel_SelectedVehicle.setName("panel_SelectedVehicle"); // NOI18N

        selectedVehicle_jComboBox.setModel(new DefaultComboBoxModel(new String[] { "<new>", "Vehicle 1", "Vehicle 2", "Vehicle 3", "Vehicle 4", "Vehicle 5" }));
        selectedVehicle_jComboBox.setName("selectedVehicle_jComboBox"); // NOI18N

        GroupLayout panel_SelectedVehicleLayout = new GroupLayout(panel_SelectedVehicle);
        panel_SelectedVehicle.setLayout(panel_SelectedVehicleLayout);
        panel_SelectedVehicleLayout.setHorizontalGroup(
            panel_SelectedVehicleLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(selectedVehicle_jComboBox, 0, 438, Short.MAX_VALUE)
        );
        panel_SelectedVehicleLayout.setVerticalGroup(
            panel_SelectedVehicleLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(selectedVehicle_jComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        panel_VehicleDescription.setBorder(BorderFactory.createTitledBorder(resourceMap.getString("panel_VehicleDescription.border.title"))); // NOI18N
        panel_VehicleDescription.setName("panel_VehicleDescription"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        vehicleDescription_jTextArea.setColumns(20);
        vehicleDescription_jTextArea.setRows(5);
        vehicleDescription_jTextArea.setName("vehicleDescription_jTextArea"); // NOI18N
        jScrollPane6.setViewportView(vehicleDescription_jTextArea);

        GroupLayout panel_VehicleDescriptionLayout = new GroupLayout(panel_VehicleDescription);
        panel_VehicleDescription.setLayout(panel_VehicleDescriptionLayout);
        panel_VehicleDescriptionLayout.setHorizontalGroup(
            panel_VehicleDescriptionLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPane6, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panel_VehicleDescriptionLayout.setVerticalGroup(
            panel_VehicleDescriptionLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPane6, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        panel_Author.setBorder(BorderFactory.createTitledBorder(resourceMap.getString("panel_Author.border.title"))); // NOI18N
        panel_Author.setName("panel_Author"); // NOI18N

        author_jTextField.setName("author_jTextField"); // NOI18N

        GroupLayout panel_AuthorLayout = new GroupLayout(panel_Author);
        panel_Author.setLayout(panel_AuthorLayout);
        panel_AuthorLayout.setHorizontalGroup(
            panel_AuthorLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(author_jTextField, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panel_AuthorLayout.setVerticalGroup(
            panel_AuthorLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(author_jTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        panel_Preview.setBorder(BorderFactory.createTitledBorder(resourceMap.getString("panel_Preview.border.title"))); // NOI18N
        panel_Preview.setName("panel_Preview"); // NOI18N

        panel_Processing.setName("panel_Processing"); // NOI18N
        panel_Processing.setLayout(new BorderLayout());

        GroupLayout panel_PreviewLayout = new GroupLayout(panel_Preview);
        panel_Preview.setLayout(panel_PreviewLayout);
        panel_PreviewLayout.setHorizontalGroup(
            panel_PreviewLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(panel_Processing, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panel_PreviewLayout.setVerticalGroup(
            panel_PreviewLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(panel_Processing, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        panel_Processing.add(embed, BorderLayout.CENTER);

        GroupLayout tab_PropertiesLayout = new GroupLayout(tab_Properties);
        tab_Properties.setLayout(tab_PropertiesLayout);
        tab_PropertiesLayout.setHorizontalGroup(
            tab_PropertiesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(tab_PropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_PropertiesLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(panel_SelectedVehicle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tab_PropertiesLayout.createSequentialGroup()
                        .addGroup(tab_PropertiesLayout.createParallelGroup(Alignment.TRAILING)
                            .addComponent(panel_VehicleName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_VehicleDescription, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(tab_PropertiesLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(panel_Preview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_Author, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tab_PropertiesLayout.setVerticalGroup(
            tab_PropertiesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(tab_PropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_SelectedVehicle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(tab_PropertiesLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(panel_Author, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_VehicleName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(tab_PropertiesLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(panel_VehicleDescription, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Preview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabContainer.addTab("Properties", tab_Properties);

        tab_Design.setName("tab_Design"); // NOI18N

        GroupLayout tab_DesignLayout = new GroupLayout(tab_Design);
        tab_Design.setLayout(tab_DesignLayout);
        tab_DesignLayout.setHorizontalGroup(
            tab_DesignLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        tab_DesignLayout.setVerticalGroup(
            tab_DesignLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        tabContainer.addTab(resourceMap.getString("tab_Design.TabConstraints.tabTitle"), tab_Design); // NOI18N

        button_Save.setText(resourceMap.getString("button_Save.text")); // NOI18N
        button_Save.setName("button_Save"); // NOI18N

        button_SaveAs.setText(resourceMap.getString("button_SaveAs.text")); // NOI18N
        button_SaveAs.setName("button_SaveAs"); // NOI18N

        ActionMap actionMap = Application.getInstance(VehiclesApp.class).getContext().getActionMap(VehicleEditor.class, this);
        button_Cancel.setAction(actionMap.get("cancel")); // NOI18N
        button_Cancel.setText(resourceMap.getString("button_Cancel.text")); // NOI18N
        button_Cancel.setName("button_Cancel"); // NOI18N

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(button_Save)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(button_SaveAs)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(button_Cancel)
                .addContainerGap())
            .addComponent(tabContainer, GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabContainer, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(button_Cancel)
                    .addComponent(button_SaveAs)
                    .addComponent(button_Save))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VehicleEditor().setVisible(true);
//            }
//        });
//    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField author_jTextField;
    private JButton button_Cancel;
    private JButton button_Save;
    private JButton button_SaveAs;
    private JScrollPane jScrollPane6;
    private JPanel panel_Author;
    private JPanel panel_Preview;
    private JPanel panel_Processing;
    private JPanel panel_SelectedVehicle;
    private JPanel panel_VehicleDescription;
    private JPanel panel_VehicleName;
    private JComboBox selectedVehicle_jComboBox;
    private JTabbedPane tabContainer;
    private JPanel tab_Design;
    private JPanel tab_Properties;
    private JTextArea vehicleDescription_jTextArea;
    private JTextField vehicleName_jTextField;
    // End of variables declaration//GEN-END:variables
    private PApplet embed;
}
